services:
  HomeAssistant:
    image: homeassistant/home-assistant:latest
    container_name: HomeAssistant
    restart: unless-stopped
    networks:
      vlan107:
        ipv4_address: 192.168.107.9
    environment:
      - TZ=Asia/Taipei
    volumes:
      - .:/config

  nmap:
    image: instrumentisto/nmap:latest
    container_name: Nmap
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./Nmap:/data
    entrypoint:
      - /bin/sh
      - -c
      - |
        sleep 120
        while true; do
          if nmap -sn -PR 192.168.0.203 | grep -q "192.168.0.203"; then
            printf 1 > /data/zack_present
          else
            printf 0 > /data/zack_present
          fi
          sleep 300
        done

networks:
  vlan107:
    external: true